
---
- name: Installing Jenkins
  hosts: jenkinsserver
  tasks:
   - name: Installing Java
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: Download Jenkins.war
     get_url:
      url: https://get.jenkins.io/war-stable/2.277.1/jenkins.war
      dest: /home/ubuntu
- name: Installing tomcat9 and tomcat9-admin
  hosts: tomcatserver
  tasks:
   - name: Installing tomcat9
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9,b: yes}
      - {a: tomcat9-admin,b: no}
   - name: copying tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Restart tomcat service
     service:
      name: tomcat9
      state: restarted
...       
