---
- name: create user
  hosts: all
  tasks:
   - name: create multiple users
     user:
      name: "{{item.a}}"
      password: "{{item.b}}"
     with_items:
      - {a: purvi,b: purvi}
      - {a: arnav,b: arnav}
...      
